# Generated by Django 4.2.18 on 2025-01-27 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='on_work_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
