# Generated by Django 4.2.16 on 2025-06-09 23:30

from django.db import migrations
import uuid


def create_sample_data(apps, schema_editor):
    Exercise = apps.get_model('api', 'Exercise')
    TreatmentTemplate = apps.get_model('api', 'TreatmentTemplate')
    TemplateExercise = apps.get_model('api', 'TemplateExercise')
    
    # Create sample exercises
    exercises = [
        {
            'name': 'Wall Crawl',
            'body_part': 'left_shoulder',
            'category': 'ROM',
            'difficulty': 'beginner',
            'default_metrics': {'flexion': 90, 'hold_sec': 5},
            'instructions': 'Stand facing a wall. Place your hand on the wall and slowly crawl your fingers up the wall as high as comfortable.'
        },
        {
            'name': 'Shoulder Flexion',
            'body_part': 'right_shoulder',
            'category': 'ROM',
            'difficulty': 'beginner',
            'default_metrics': {'flexion': 120, 'hold_sec': 3},
            'instructions': 'Raise your arm forward and up as high as comfortable. Hold the position.'
        },
        {
            'name': 'Sit to Stand',
            'body_part': 'hip',
            'category': 'Functional',
            'difficulty': 'intermediate',
            'default_metrics': {'repetitions': 10, 'hold_sec': 2},
            'instructions': 'Sit in a chair with feet flat on floor. Stand up without using your hands for support.'
        },
        {
            'name': 'Ankle Pumps',
            'body_part': 'left_ankle',
            'category': 'ROM',
            'difficulty': 'beginner',
            'default_metrics': {'dorsiflexion': 20, 'repetitions': 15},
            'instructions': 'Point your toes up toward your shin, then point them down. Repeat in a pumping motion.'
        },
        {
            'name': 'Knee Flexion',
            'body_part': 'right_knee',
            'category': 'ROM',
            'difficulty': 'beginner',
            'default_metrics': {'flexion': 90, 'hold_sec': 5},
            'instructions': 'Bend your knee as far as comfortable. Hold the position.'
        },
        {
            'name': 'Balance Training',
            'body_part': 'general',
            'category': 'Balance',
            'difficulty': 'intermediate',
            'default_metrics': {'hold_sec': 30, 'repetitions': 3},
            'instructions': 'Stand on one foot for as long as possible. Use support if needed.'
        },
    ]
    
    created_exercises = []
    for exercise_data in exercises:
        exercise = Exercise.objects.create(**exercise_data)
        created_exercises.append(exercise)
    
    # Create sample treatment templates
    templates = [
        {
            'name': 'Shoulder Recovery Program',
            'treatment_type': 'joint_specific',
            'treatment_subtype': 'shoulder_rom',
            'condition': 'Frozen Shoulder',
            'description': 'Comprehensive shoulder rehabilitation program for patients with frozen shoulder or post-surgery recovery.',
            'default_frequency': '3x/week',
            'estimated_duration_weeks': 8,
            'exercises': [
                {'exercise': created_exercises[0], 'order': 1, 'required': True, 'reps': 10, 'sets': 3, 'pain': 4},  # Wall Crawl
                {'exercise': created_exercises[1], 'order': 2, 'required': True, 'reps': 8, 'sets': 2, 'pain': 5},   # Shoulder Flexion
            ]
        },
        {
            'name': 'Functional Mobility Program',
            'treatment_type': 'functional',
            'treatment_subtype': 'sit_to_stand',
            'condition': 'General Mobility',
            'description': 'Functional training program to improve daily living activities and overall mobility.',
            'default_frequency': 'daily',
            'estimated_duration_weeks': 6,
            'exercises': [
                {'exercise': created_exercises[2], 'order': 1, 'required': True, 'reps': 10, 'sets': 3, 'pain': 3},  # Sit to Stand
                {'exercise': created_exercises[5], 'order': 2, 'required': False, 'reps': 3, 'sets': 1, 'pain': 2}, # Balance Training
            ]
        },
        {
            'name': 'Lower Extremity Recovery',
            'treatment_type': 'joint_specific',
            'treatment_subtype': 'knee_flexion',
            'condition': 'Post-Surgery Knee',
            'description': 'Lower extremity rehabilitation program for post-surgical knee and ankle recovery.',
            'default_frequency': '2x/day',
            'estimated_duration_weeks': 12,
            'exercises': [
                {'exercise': created_exercises[3], 'order': 1, 'required': True, 'reps': 15, 'sets': 2, 'pain': 2},  # Ankle Pumps
                {'exercise': created_exercises[4], 'order': 2, 'required': True, 'reps': 8, 'sets': 3, 'pain': 4},   # Knee Flexion
                {'exercise': created_exercises[2], 'order': 3, 'required': False, 'reps': 5, 'sets': 2, 'pain': 3}, # Sit to Stand
            ]
        },
        {
            'name': 'Pain Management Program',
            'treatment_type': 'pain_adapted',
            'treatment_subtype': 'gentle_movement',
            'condition': 'Chronic Pain',
            'description': 'Gentle movement program designed for patients with chronic pain conditions.',
            'default_frequency': '2x/week',
            'estimated_duration_weeks': 10,
            'exercises': [
                {'exercise': created_exercises[3], 'order': 1, 'required': True, 'reps': 10, 'sets': 1, 'pain': 2},  # Ankle Pumps
                {'exercise': created_exercises[0], 'order': 2, 'required': False, 'reps': 5, 'sets': 1, 'pain': 3}, # Wall Crawl
            ]
        },
    ]
    
    for template_data in templates:
        exercises_data = template_data.pop('exercises')
        template = TreatmentTemplate.objects.create(**template_data)
        
        for exercise_data in exercises_data:
            TemplateExercise.objects.create(
                template_id=template,
                exercise_id=exercise_data['exercise'],
                default_target_metrics=exercise_data['exercise'].default_metrics,
                default_repetitions=exercise_data['reps'],
                default_sets=exercise_data['sets'],
                default_pain_threshold=exercise_data['pain'],
                order_in_template=exercise_data['order'],
                is_required=exercise_data['required'],
            )


def reverse_sample_data(apps, schema_editor):
    Exercise = apps.get_model('api', 'Exercise')
    TreatmentTemplate = apps.get_model('api', 'TreatmentTemplate')
    TemplateExercise = apps.get_model('api', 'TemplateExercise')
    
    # Delete all sample data
    TemplateExercise.objects.all().delete()
    TreatmentTemplate.objects.all().delete()
    Exercise.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_sample_data),
    ]
