# Generated by Django 4.2.16 on 2025-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250610_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='detection_rules',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]

# Generated by Django 4.2.18 on 2025-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250610_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='detection_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
