# Generated by Django 4.2.18 on 2025-02-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_status_customuser_statu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='statu',
            new_name='status',
        ),
    ]
