# Generated by Django 4.2.18 on 2025-09-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exercise_detection_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('dtw', 'DTW Recognition'), ('clf', 'Classifier Model')], default='dtw', max_length=10)),
                ('params_json', models.JSONField(default=dict)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq_json', models.JSONField(default=dict)),
                ('length', models.IntegerField()),
                ('feature_dim', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.action')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reps', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('metrics_json', models.JSONField(default=dict)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.action')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionSample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(blank=True, max_length=255)),
                ('keypoints_json', models.JSONField(default=dict)),
                ('fps', models.IntegerField(default=30)),
                ('weak_labels_json', models.JSONField(default=dict)),
                ('refined_labels_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.action')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
