# Generated by Django 4.2.18 on 2025-02-02 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
