# Generated by Django 4.2.18 on 2025-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_system_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_at']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_code',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='api_appoint_therapi_54c687_idx',
            old_name='api_appoint_therapist_4a8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='api_appoint_patient_c527c9_idx',
            old_name='api_appoint_patient_5a8c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='availabilityslot',
            new_name='api_availab_therapi_caf2a1_idx',
            old_name='api_availab_therapist_2b8c8a_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
