# Generated by Django 4.2.18 on 2025-09-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(choices=[('meeting', 'Meeting'), ('personal', 'Personal'), ('break', 'Break'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Additional details', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist_id', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
        migrations.AddIndex(
            model_name='unavailableslot',
            index=models.Index(fields=['therapist_id', 'start_at'], name='api_unavail_therapi_ba9c36_idx'),
        ),
    ]
