# Generated by Django 4.2.18 on 2025-09-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_unavailableslot_delete_availabilityslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailableslot',
            name='reason',
        ),
    ]
