# Generated by Django 4.2.18 on 2025-02-17 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='employment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentId', models.CharField(editable=False, max_length=50, unique=True)),
                ('appointmentDateTime', models.DateTimeField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.patient')),
                ('therapistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.therapist')),
            ],
        ),
    ]
