# Generated by Django 4.2.18 on 2025-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_therapist_employment_date_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patientId',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='therapistId',
            new_name='therapist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
