# Generated by Django 4.2.18 on 2025-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment_cancel_reason_appointment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='session_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
