# Generated by Django 4.2.18 on 2025-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20250918_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_message',
            field=models.TextField(blank=True, help_text='Message from patient to therapist', null=True),
        ),
    ]
