# Generated by Django 4.2.18 on 2025-09-23 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appointment_patient_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='objective_findings',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies to medications, food, or environmental factors.', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='family_history',
            field=models.TextField(blank=True, help_text='Information about health of blood relatives, e.g., cancer, hypertension, diabetes.', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medications',
            field=models.TextField(blank=True, help_text='Comprehensive list of current and past medications, including dosage and frequency.', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='past_medical_history',
            field=models.TextField(blank=True, help_text='Details of any diagnosed medical conditions, including chronic illnesses and past significant illnesses.', null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='surgical_history',
            field=models.TextField(blank=True, help_text='List of past surgeries with procedures and dates.', null=True),
        ),
    ]
