# Generated by Django 4.2.16 on 2025-09-23 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_objective_findings_medicalhistory_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='recorded_by_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['therapist', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
