# Generated by Django 4.2.16 on 2025-09-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_patient_medicalhistory_patient_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='creation_method',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='template_id',
        ),
        migrations.DeleteModel(
            name='TemplateExercise',
        ),
        migrations.DeleteModel(
            name='TreatmentTemplate',
        ),
    ]
