# Generated by Django 4.2.16 on 2025-09-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_treatmenttemplate_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='notes',
            new_name='goal_notes',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='estimated_end_date',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_goals',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_subtype',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
