# Generated by Django 4.2.16 on 2025-09-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_notes_treatment_goal_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentexercise',
            old_name='progress_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='treatmentexercise',
            old_name='pain_threshold',
            new_name='reps_per_set',
        ),
        migrations.RemoveField(
            model_name='treatmentexercise',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='treatmentexercise',
            name='sets',
        ),
    ]
