# Generated by Django 4.2.18 on 2025-09-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_progress_notes_treatmentexercise_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='default_metrics',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='demo_video_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='detection_rules',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='is_active',
        ),
        migrations.AddField(
            model_name='exercise',
            name='action_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='api.action'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('upper_body', 'Upper Body'), ('lower_body', 'Lower Body'), ('full_body', 'Full Body')], default='upper_body', max_length=20),
        ),
    ]
