# Generated by Django 4.2.18 on 2025-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_exercise_body_part_remove_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentexercise',
            name='target_metrics',
        ),
        migrations.AddField(
            model_name='treatmentexercise',
            name='duration_per_set',
            field=models.IntegerField(blank=True, help_text='Duration per set in seconds', null=True),
        ),
        migrations.AddField(
            model_name='treatmentexercise',
            name='sets',
            field=models.IntegerField(default=1, help_text='Number of sets for this exercise'),
        ),
    ]
