# Generated by Django 4.2.18 on 2025-10-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_treatmentexercise_target_metrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecord',
            name='actual_metrics',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='pain_level',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='patient_notes',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='session_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='therapist_notes',
        ),
    ]
