# Generated by Django 4.2.18 on 2025-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_exerciserecord_actual_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='avg_duration',
            field=models.FloatField(blank=True, help_text='Average time per repetition in seconds', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Exercise session end time', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='pause_count',
            field=models.IntegerField(default=0, help_text='Number of pauses during exercise'),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='repetition_times',
            field=models.JSONField(blank=True, default=list, help_text='Array of time taken for each repetition in seconds', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Exercise session start time', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='total_duration',
            field=models.FloatField(blank=True, help_text='Total exercise duration in seconds', null=True),
        ),
    ]
