# Generated by Django 4.2.18 on 2025-11-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_exerciserecord_avg_duration_exerciserecord_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecord',
            name='avg_duration',
        ),
    ]
