# Generated by Django 4.2.18 on 2025-11-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_exerciserecord_avg_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='status',
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
