# Generated by Django 4.2.18 on 2025-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_treatment_status_treatment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_role',
            field=models.CharField(choices=[('CenterAdmin', 'Center Admin'), ('SuperAdmin', 'Super Admin')], default='CenterAdmin', max_length=50),
        ),
    ]
