# Generated by Django 4.2.18 on 2025-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_admin_admin_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionSession',
        ),
    ]
