# Generated by Django 4.2.18 on 2025-11-26 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_delete_actionsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'therapist']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatments', to=settings.AUTH_USER_MODEL),
        ),
    ]
