# Generated by Django 4.2.18 on 2025-11-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_treatment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='treatmentexercise',
            name='duration_per_set',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
