# Generated by Django 4.2.16 on 2025-12-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_exercise_options_remove_exercise_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsample',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actiontemplate',
            name='action',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='action_id',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionSample',
        ),
        migrations.DeleteModel(
            name='ActionTemplate',
        ),
    ]
