# Generated by Django 4.2.18 on 2025-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_delete_action_learning_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='activity_name',
            field=models.CharField(blank=True, help_text='Rehab Engine activity name (must match supported model labels)', max_length=120, null=True),
        ),
    ]
