# Generated by Django 4.2.16 on 2025-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_exercise_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentexercise',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Maximum duration per rep in seconds. Exercise will stop if rep exceeds this duration.', null=True),
        ),
    ]
