# Generated by Django 4.2.18 on 2025-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_treatmentexercise_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentexercise',
            name='duration',
            field=models.IntegerField(default=60, help_text='Maximum duration per rep in seconds. Exercise will stop if rep exceeds this duration.'),
        ),
    ]
