# Generated by Django 4.2.18 on 2025-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_treatmentexercise_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentexercise',
            name='duration',
            field=models.IntegerField(default=1, help_text='Time to complete the entire exercise within this duration (in minutes). Exercise will stop if it exceeds this time.'),
        ),
    ]
