# Generated by Django 4.2.16 on 2025-12-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_treatmentexercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='demo_video_url',
            field=models.CharField(blank=True, help_text='URL path to demo video (e.g., /media/exercise_videos/exercise_xxx.mp4)', max_length=255, null=True),
        ),
    ]
