# Generated by Django 4.2.18 on 2025-12-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_exercise_demo_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='rep_sparc_scores',
            field=models.JSONField(blank=True, default=list, help_text='Spectral Arc Length smoothness score for each repetition', null=True),
        ),
    ]
