# Generated by Django 4.2.16 on 2025-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_exerciserecord_rep_sparc_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='rep_rom_scores',
            field=models.JSONField(blank=True, default=list, help_text='Range of Motion per repetition', null=True),
        ),
    ]
