# Generated by Django 4.2.18 on 2025-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_exerciserecord_rep_rom_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='target_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Assigned duration limit (minutes) when this session was recorded', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='target_reps_per_set',
            field=models.IntegerField(blank=True, help_text='Assigned reps per set when this session was recorded', null=True),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='target_sets',
            field=models.IntegerField(blank=True, help_text='Assigned total sets when this session was recorded', null=True),
        ),
    ]
